project_id = "swereqlfseezobfmmrrg"

[functions.submit-form]
verify_jwt = false

[functions.facebook-auth]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.initiate-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.check-subscriptions]
verify_jwt = false
